#!/bin/sh

current_song="$(mpc -f '[%albumartist% - ]%title%' current)"

play_status="$(mpc status | awk -v RS='' -v FS='\n' '{print $2}' | awk '{print $1}')"

case $play_status in
	"[playing]" )
		echo -ne "^c#b4a4f4^ ^c#eeffff^${current_song}"
		;;
	"[paused]" )
		echo -ne "^c#b4a4f4^ ^c#eeffff^${current_song}"
		;;
	* )
		;;
esac
