#!/bin/sh

OIFS=$IFS

IFS=$'\n' connecteddevices=($(nmcli device | awk '$3=="connected" {$1=$2=$3=""; print $0}'))

IFS=$OIFS

if [[ ! -n $connecteddevices ]]; then
	netstatus="^c#ff757f^ ^c#eeffff^Not Connected"
else
	device=`echo ${connecteddevices[0]}`

	if [[ $device == "Wired connection 1" ]]; then
	    netstatus="^c#b4a4f4^ ^c#eeffff^Ethernet"
	else
	    netstatus="^c#b4a4f4^ ^c#eeffff^${device}"
	fi
fi

echo -ne "$netstatus"
