#!/bin/sh

nord_status="$(nordvpn status | awk '$2 ~ /Status:/ {print $3}')"

if [[ $nord_status == "Connected" ]]; then
	nord_server="$(nordvpn status | awk '$3 ~ /nordvpn.com/ {print $3}')"
    echo -ne "^c#81a1c1^ ^d^${nord_server}"
fi
