#!/bin/sh

status="$(cat /sys/class/power_supply/BAT0/status)"
battery="$(cat /sys/class/power_supply/BAT0/capacity)"
if [[ "${status}" == "Charging" ]]; then
    echo -ne "^c#EBCB8B^ ^d^${battery}%"
else
	if [[ $battery -gt 97 ]]; then
		echo -ne "^c#3ea290^ ^d^${battery}%"
	elif [[ $battery -le 97 && $battery -gt 50 ]]; then
		echo -ne "^c#81a1c1^ ^d^${battery}%"
	elif [[ $battery -le 50 && $battery -gt 20 ]]; then
		echo -ne "^c#81a1c1^ ^d^${battery}%"
	else
		echo -ne "^c#BF616a^ ^d^${battery}%"
	fi
fi
