#!/bin/sh

SPOTIFYD_DEST="org.mpris.MediaPlayer2.spotifyd"
SPOTIFYD_PATH="/org/mpris/MediaPlayer2"
SPOTIFYD_MEMB="org.mpris.MediaPlayer2.Player"

function get_status {
STATUS=`\
dbus-send --print-reply \
--dest=org.mpris.MediaPlayer2.spotifyd \
/org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
string:"org.mpris.MediaPlayer2.Player" string:'PlaybackStatus' \
| grep -Ev "^method" \
| awk '{ print $3 }' `
}


function get_metadata {
read -d '' RAW_METADATA << EOF \
`dbus-send --print-reply \
--dest=$SPOTIFYD_DEST \
$SPOTIFYD_PATH \
org.freedesktop.DBus.Properties.Get \
string:"$SPOTIFYD_MEMB" string:'Metadata' \
| grep -Ev "^method" \
| grep -Eo '("(.*)")|(\b[0-9][a-zA-Z0-9.]*\b)' \
| sed -E '2~2 a|' \
| tr -d '\n' \
| sed -E 's/\|/\n/g' \
| sed -E 's/(xesam:)|(mpris:)//' \
| sed -E 's/^"//' \
| sed -E 's/"$//' \
| sed -E 's/"+/|/' \
| sed -E 's/ +/ /g'`
EOF

#IFS=' ' read -r -a METADATA <<< $RAW_METADATA
}

function print_metadata {
$RAW_METADATA \
| grep -E "(title)|(album)|(artist)" \
| sed 's/^\(.\)/\U\1/' \
| column -t -s'|'
}

get_status
get_metadata

#echo $RAW_METADATA | grep -E "(title)|(album)|(artist)" | sed 's/^\(.\)/\U\1/' | column -t -s'|'

print_metadata


#for data in "${METADATA[@]}"; do
#	echo $data
#done
